import Header from '@/components/header';
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/footer'

export const metadata: Metadata = {
    title: 'Nyarlathotep',
    description: 'Generated by create next app',
}


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                <>{children}</>
                <Footer />
            </body>
        </html>
    )
}
